# Generated by Django 4.1.7 on 2023-06-23 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('imageUrl', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('in_stock', models.BooleanField(default=True)),
                ('product_available', models.CharField(max_length=255)),
                ('reviews', models.ManyToManyField(blank=True, to='products.review')),
                ('tags', models.ManyToManyField(blank=True, to='products.product')),
            ],
        ),
    ]
